name: another_authenticator
description: A two-factor authentication app implemented with Flutter.
publish_to: none

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Flutter team dependencies
  cupertino_icons: ^1.0.3
  intl: ^0.18.0

  # Flutter plugins
  path_provider: ^2.0.2
  url_launcher: ^6.0.9
  package_info: ^2.0.2

  # Internal
  another_authenticator_totp:
    path: ./totp

  # External
  barcode_scan2: 4.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true

  assets:
    - graphics/icon.png
    - assets/licenses/
