name: another_authenticator
description: A two-factor authentication app implemented with Flutter.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # Flutter team dependencies
  crypto: ^3.0.1
  cupertino_icons: ^1.0.3

  # Flutter plugins
  path_provider: ^2.0.2
  url_launcher: ^6.0.9
  package_info: ^2.0.2

  barcode_scan2: 4.2.3
  uuid: 3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - graphics/icon.png
    - assets/licenses/dartlang-crypto.txt
    - assets/licenses/flutter-flutter.txt
    - assets/licenses/flutter-cupertino_icons.txt
    - assets/licenses/dartlang-crypto.txt
    - assets/licenses/apptreesoftware-flutter_barcode_scanner.txt
    - assets/licenses/daegalus-dart-uuid.txt
    - assets/licenses/brianegan-flutter_architecture_samples.txt
