name: another_authenticator
description: "Another two-factor authentication app."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Flutter team dependencies
  cupertino_icons: ^1.0.8
  intl: ^0.19.0

  # Flutter plugins
  path_provider: ^2.1.4
  url_launcher: ^6.3.0
  package_info_plus: ^8.0.2

  # Internal
  another_authenticator_totp:
    path: ./totp
  another_authenticator_state:
    path: ./state

  # External
  barcode_scan2: ^4.3.3
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - graphics/icon.png