name: another_authenticator_otp
description: OTP library used by another_authenticator.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  crypto: ^3.0.5

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.2
