name: another_authenticator_state
description: State for Another Authenticator.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  uuid: 4.4.0

  # Internal
  another_authenticator_otp:
    path: ../otp

  sqflite: ^2.3.3

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.2
