name: another_authenticator_state
description: State for Another Authenticator.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.0.5

dependencies:
  uuid: 3.0.7

  # Internal
  another_authenticator_totp:
    path: ../totp

dev_dependencies:
  lints: ^2.1.1
  test: ^1.24.3
