name: another_authenticator_state
description: State for Another Authenticator.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  uuid: 4.2.2

  # Internal
  another_authenticator_totp:
    path: ../totp

  sqflite: ^2.3.0
  path: ^1.8.3

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.0
