name: Another Authenticator

on:
  push:
    branches:
      - '*'

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.x'
        channel: 'stable'

    - run: dart test
      working-directory: ./totp

    - run: dart test
      working-directory: ./state

    - run: flutter pub get
    - run: flutter test
    - run: flutter build apk

    - name: Save artifacts
      uses: actions/upload-artifact@v4
      with:
        name: apk
        path: build/app/outputs/apk/release/app-release.apk
